# Generated by Django 4.0 on 2021-12-15 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='user',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cuenta.usuario'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaEdicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
