# Generated by Django 4.0 on 2021-12-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_remove_publicacion_user_publicacion_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaEdicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
